ks_graph_to_dataframe = function(graph1,graph2,name1,name2,column_name1="Data set1",column_name2="Data set2"){
  #The function takes the bipartite graphs from the function ks_make_bipartite_graph from two different data set and creates an appropriate output,
  #listing the metabolites and their number of appearences in paris, triplets and quadruples
  
  ####Input
  #graph1: a bipartite graph of the first data set, generated by ks_make_bipartite_graph
  #graph2: a bipartite graph of the second data set, generated by ks_make_bipartite_graph
  #name1: the names of the metabolites of the first data set
  #name2: the names of the metabolites of the second data set
  #column_name1: string which is used to change the column name to match the data set
  #column_name2: string which is used to change the column name to match the data set
  
  ####Output
  # df: data.frame containing the metabolite names and their node degree, representing the their number of appearences in paris, triplets and quadruples
  
  
 df=   data.frame(names(sort(degree(graph1,v=name1))),
                  sort(degree(graph1,v=name1)),
             names(sort(degree(graph2,v=name2))),
             sort(degree(graph2,v=name2)),
             row.names = NULL)
 
  colnames(df)<-c("Metabolites",column_name1,"Metabolites",column_name2)
  return(df)
}